const TEST_CATEGORIES = {
  // Hormones & Vitamins
  dht: 'Hormones & Vitamins',
  vit_d_25_oh: 'Hormones & Vitamins',
  vit_b12: 'Hormones & Vitamins',
  psa: 'Hormones & Vitamins',
  t3_total: 'Hormones & Vitamins',
  t4_total: 'Hormones & Vitamins',
  tsh_ultra: 'Hormones & Vitamins',

  // Cardiac, Iron & Diabetes
  hs_crp: 'Cardiac, Iron & Diabetes',
  iron_total: 'Cardiac, Iron & Diabetes',
  tibc: 'Cardiac, Iron & Diabetes',
  transferrin_sat: 'Cardiac, Iron & Diabetes',
  uibc: 'Cardiac, Iron & Diabetes',
  fbg: 'Cardiac, Iron & Diabetes',
  hba1c: 'Cardiac, Iron & Diabetes',
  abg: 'Cardiac, Iron & Diabetes',

  // Lipid Profile
  cholesterol_total: 'Lipid Profile',
  hdl_direct: 'Lipid Profile',
  ldl_direct: 'Lipid Profile',
  triglycerides: 'Lipid Profile',
  tc_hdl_ratio: 'Lipid Profile',
  trig_hdl_ratio: 'Lipid Profile',
  ldl_hdl_ratio: 'Lipid Profile',
  hdl_ldl_ratio: 'Lipid Profile',
  non_hdl: 'Lipid Profile',
  vldl: 'Lipid Profile',

  // Liver, Kidney & Electrolytes
  amylase: 'Liver, Kidney & Electrolytes',
  alp: 'Liver, Kidney & Electrolytes',
  bilirubin_total: 'Liver, Kidney & Electrolytes',
  bilirubin_direct: 'Liver, Kidney & Electrolytes',
  bilirubin_indirect: 'Liver, Kidney & Electrolytes',
  ggt: 'Liver, Kidney & Electrolytes',
  sgot: 'Liver, Kidney & Electrolytes',
  sgpt: 'Liver, Kidney & Electrolytes',
  sgot_sgpt_ratio: 'Liver, Kidney & Electrolytes',
  protein_total: 'Liver, Kidney & Electrolytes',
  albumin_serum: 'Liver, Kidney & Electrolytes',
  globulin_serum: 'Liver, Kidney & Electrolytes',
  alb_glob_ratio: 'Liver, Kidney & Electrolytes',
  magnesium: 'Liver, Kidney & Electrolytes',
  ldh: 'Liver, Kidney & Electrolytes',
  phosphorous: 'Liver, Kidney & Electrolytes',
  sodium: 'Liver, Kidney & Electrolytes',
  potassium: 'Liver, Kidney & Electrolytes',
  chloride: 'Liver, Kidney & Electrolytes',
  bun: 'Liver, Kidney & Electrolytes',
  creatinine_serum: 'Liver, Kidney & Electrolytes',
  bun_creat_ratio: 'Liver, Kidney & Electrolytes',
  urea_calc: 'Liver, Kidney & Electrolytes',
  calcium: 'Liver, Kidney & Electrolytes',
  urea_creat_ratio: 'Liver, Kidney & Electrolytes',
  uric_acid: 'Liver, Kidney & Electrolytes',
  egfr: 'Liver, Kidney & Electrolytes',

  // Hematology
  esr: 'Hematology',
  hemoglobin: 'Hematology',
  pcv: 'Hematology',
  rbc_total: 'Hematology',
  mcv: 'Hematology',
  mch: 'Hematology',
  mchc: 'Hematology',
  rdw_sd: 'Hematology',
  rdw_cv: 'Hematology',
  rdwi: 'Hematology',
  mentzer_index: 'Hematology',
  wbc_total: 'Hematology',
  neutrophils_pct: 'Hematology',
  lymphocytes_pct: 'Hematology',
  monocytes_pct: 'Hematology',
  eosinophils_pct: 'Hematology',
  basophils_pct: 'Hematology',
  ig_pct: 'Hematology',
  nrbc_pct: 'Hematology',
  neutrophils_abs: 'Hematology',
  lymphocytes_abs: 'Hematology',
  monocytes_abs: 'Hematology',
  basophils_abs: 'Hematology',
  eosinophils_abs: 'Hematology',
  ig_abs: 'Hematology',
  nrbc_abs: 'Hematology',
  platelet_count: 'Hematology',
  mpv: 'Hematology',
  pdw: 'Hematology',
  plcr: 'Hematology',
  pct: 'Hematology',

  // Urinalysis
  urine_volume: 'Urinalysis',
  urine_colour: 'Urinalysis',
  urine_appearance: 'Urinalysis',
  urine_specific_gravity: 'Urinalysis',
  urine_ph: 'Urinalysis',
  urine_protein: 'Urinalysis',
  urine_glucose: 'Urinalysis',
  urine_ketone: 'Urinalysis',
  urine_bilirubin: 'Urinalysis',
  urine_urobilinogen: 'Urinalysis',
  urine_bile_salt: 'Urinalysis',
  urine_bile_pigment: 'Urinalysis',
  urine_blood: 'Urinalysis',
  urine_nitrite: 'Urinalysis',
  urine_leucocyte_esterase: 'Urinalysis',
  urine_mucus: 'Urinalysis',
  urine_rbc: 'Urinalysis',
  urine_pus_cells: 'Urinalysis',
  urine_epithelial_cells: 'Urinalysis',
  urine_casts: 'Urinalysis',
  urine_crystals: 'Urinalysis',
  urine_bacteria: 'Urinalysis',
  urine_yeast: 'Urinalysis',
  urine_parasite: 'Urinalysis',
};

const CATEGORY_ORDER = [
  'Hormones & Vitamins',
  'Cardiac, Iron & Diabetes',
  'Lipid Profile',
  'Liver, Kidney & Electrolytes',
  'Hematology',
  'Urinalysis',
];

const REPORT_STATUS = {
  PENDING: 'pending',
  PROCESSING: 'processing',
  COMPLETED: 'completed',
  FAILED: 'failed',
};

module.exports = { TEST_CATEGORIES, CATEGORY_ORDER, REPORT_STATUS };
