/**
 * Data migration: add description and category_order to all test_definitions,
 * update display names, and insert missing tests.
 */

const TEST_UPDATES = [
  {"test_key":"dht","display_name":"Dihydrotestosterone (DHT)","category_order":1,"description":"A potent androgen derived from testosterone via 5-alpha reductase. Elevated levels are associated with male-pattern baldness, benign prostatic hyperplasia, and acne. Low levels may indicate 5-alpha reductase deficiency."},
  {"test_key":"vit_d_25_oh","display_name":"Vitamin D (25-OH)","category_order":1,"description":"Measures the storage form of vitamin D. Deficiency is common and linked to bone loss, muscle weakness, immune dysfunction, and increased risk of depression. Levels <20 ng/mL are deficient; 20–50 ng/mL is sufficient."},
  {"test_key":"vit_b12","display_name":"Vitamin B12","category_order":1,"description":"Essential for red blood cell formation, neurological function, and DNA synthesis. Deficiency causes megaloblastic anemia, peripheral neuropathy, and cognitive impairment. Risk is higher in vegans and those on metformin."},
  {"test_key":"psa","display_name":"Prostate-Specific Antigen (PSA)","category_order":1,"description":"A protein produced by the prostate gland. Elevated PSA may indicate benign prostatic hyperplasia, prostatitis, or prostate cancer. Used for prostate cancer screening and monitoring treatment response."},
  {"test_key":"t3_total","display_name":"T3 Total (Triiodothyronine)","category_order":1,"description":"The active thyroid hormone responsible for regulating metabolism, heart rate, and body temperature. Low T3 indicates hypothyroidism; high T3 indicates hyperthyroidism or T3 toxicosis."},
  {"test_key":"t4_total","display_name":"T4 Total (Thyroxine)","category_order":1,"description":"The primary hormone secreted by the thyroid gland, converted to T3 in tissues. Elevated T4 suggests hyperthyroidism; low T4 suggests hypothyroidism. Interpreted alongside TSH for complete thyroid assessment."},
  {"test_key":"tsh_ultra","display_name":"TSH (Ultrasensitive)","category_order":1,"description":"Thyroid-stimulating hormone secreted by the pituitary. The most sensitive marker of thyroid function. High TSH indicates hypothyroidism (sluggish thyroid); low TSH indicates hyperthyroidism or pituitary suppression."},
  {"test_key":"hs_crp","display_name":"hs-CRP (High-Sensitivity C-Reactive Protein)","category_order":2,"description":"A marker of systemic inflammation. Levels >3 mg/L indicate elevated cardiovascular risk. Very high levels (>10 mg/L) suggest acute infection or tissue injury. Used alongside lipid panels for cardiovascular risk stratification."},
  {"test_key":"iron_total","display_name":"Iron (Serum Total)","category_order":2,"description":"Measures circulating iron bound to transferrin. Low values suggest iron-deficiency anemia or chronic inflammation. High values may indicate hemochromatosis or iron overload. Interpreted with TIBC and ferritin for complete iron status."},
  {"test_key":"tibc","display_name":"TIBC (Total Iron-Binding Capacity)","category_order":2,"description":"Measures the maximum amount of iron that transferrin can carry. High TIBC with low iron indicates iron deficiency. Low TIBC with high iron suggests iron overload or chronic disease."},
  {"test_key":"transferrin_sat","display_name":"Transferrin Saturation","category_order":2,"description":"Percentage of transferrin binding sites occupied by iron. Low saturation (<20%) indicates iron deficiency; high saturation (>45%) indicates iron overload or hemochromatosis."},
  {"test_key":"uibc","display_name":"UIBC (Unsaturated Iron-Binding Capacity)","category_order":2,"description":"The reserve capacity of transferrin to bind more iron. Elevated UIBC confirms iron deficiency; decreased UIBC is seen in iron overload or liver disease."},
  {"test_key":"fbg","display_name":"Fasting Blood Glucose (FBG)","category_order":2,"description":"Measures blood glucose after an 8-hour fast. Normal: <100 mg/dL. Prediabetes: 100–125 mg/dL. Diabetes: ≥126 mg/dL on two separate tests. Key screening test for diabetes mellitus."},
  {"test_key":"hba1c","display_name":"HbA1c (Glycated Hemoglobin)","category_order":2,"description":"Reflects average blood glucose over the past 2–3 months. Normal: <5.7%. Prediabetes: 5.7–6.4%. Diabetes: ≥6.5%. Used to monitor long-term glucose control and treatment effectiveness in diabetic patients."},
  {"test_key":"abg","display_name":"Arterial Blood Gas (ABG)","category_order":2,"description":"Measures oxygen, carbon dioxide, and pH of arterial blood. Used to assess respiratory and metabolic acid-base status, lung function, and oxygenation. Critical in ICU and respiratory disease management."},
  {"test_key":"cholesterol_total","display_name":"Total Cholesterol","category_order":3,"description":"Sum of all cholesterol in the blood including HDL, LDL, and VLDL. Desirable: <200 mg/dL. Borderline high: 200–239 mg/dL. High: ≥240 mg/dL. Elevated levels increase cardiovascular disease risk."},
  {"test_key":"hdl_direct","display_name":"HDL Cholesterol (Direct)","category_order":3,"description":"\"Good\" cholesterol that transports excess cholesterol to the liver for excretion. Low HDL (<40 mg/dL in men, <50 mg/dL in women) is an independent cardiovascular risk factor. High HDL (>60 mg/dL) is cardioprotective."},
  {"test_key":"ldl_direct","display_name":"LDL Cholesterol (Direct)","category_order":3,"description":"\"Bad\" cholesterol that deposits in artery walls, causing atherosclerosis. Optimal: <100 mg/dL. Near optimal: 100–129 mg/dL. Borderline high: 130–159 mg/dL. High: ≥160 mg/dL. Primary target of lipid-lowering therapy."},
  {"test_key":"triglycerides","display_name":"Triglycerides","category_order":3,"description":"The most common type of fat in the body. Normal: <150 mg/dL. Borderline high: 150–199 mg/dL. High: 200–499 mg/dL. Very high: ≥500 mg/dL. Elevated triglycerides are linked to pancreatitis and cardiovascular disease."},
  {"test_key":"tc_hdl_ratio","display_name":"Total Cholesterol / HDL Ratio","category_order":3,"description":"Cardiovascular risk predictor. Desirable: <4.0. Optimal: <3.5. A lower ratio indicates better cardiovascular protection. High ratios suggest elevated atherogenic risk even when total cholesterol is borderline."},
  {"test_key":"trig_hdl_ratio","display_name":"Triglyceride / HDL Ratio","category_order":3,"description":"A proxy for insulin resistance and small dense LDL particles. Ratio <2 is optimal; >3 suggests insulin resistance; >5 indicates high cardiovascular risk. Often more predictive than LDL alone in metabolic syndrome."},
  {"test_key":"ldl_hdl_ratio","display_name":"LDL / HDL Ratio","category_order":3,"description":"Indicates atherogenic burden relative to protective cholesterol. Optimal: <2.0. High risk: >3.0. Used alongside absolute LDL and HDL values for a more comprehensive cardiovascular risk picture."},
  {"test_key":"hdl_ldl_ratio","display_name":"HDL / LDL Ratio","category_order":3,"description":"Inverse of LDL/HDL ratio. Higher values are protective. A ratio above 0.3 is generally considered favorable for cardiovascular health."},
  {"test_key":"non_hdl","display_name":"Non-HDL Cholesterol","category_order":3,"description":"Total cholesterol minus HDL — includes all atherogenic lipoproteins (LDL, VLDL, IDL). Optimal: <130 mg/dL. Considered a better predictor of cardiovascular events than LDL alone, especially in patients with high triglycerides."},
  {"test_key":"vldl","display_name":"VLDL Cholesterol","category_order":3,"description":"Very low-density lipoprotein carries triglycerides from the liver to tissues. Calculated as triglycerides ÷ 5. Normal: 2–30 mg/dL. Elevated VLDL contributes to atherosclerosis and is closely linked to hypertriglyceridemia."},
  {"test_key":"amylase","display_name":"Amylase (Serum)","category_order":4,"description":"An enzyme produced by the pancreas and salivary glands to digest carbohydrates. Elevated amylase indicates acute pancreatitis, salivary gland inflammation, or intestinal injury. Levels >3× normal are strongly suggestive of pancreatitis."},
  {"test_key":"alp","display_name":"ALP (Alkaline Phosphatase)","category_order":4,"description":"An enzyme found in the liver, bile ducts, and bone. Elevated ALP suggests bile duct obstruction, liver disease, or bone disorders (Paget's disease, metastases). Children and adolescents normally have higher ALP due to bone growth."},
  {"test_key":"bilirubin_total","display_name":"Bilirubin (Total)","category_order":4,"description":"A yellow pigment produced by red blood cell breakdown. High total bilirubin causes jaundice and indicates liver disease, bile duct obstruction, or hemolysis. Normal: 0.2–1.2 mg/dL."},
  {"test_key":"bilirubin_direct","display_name":"Bilirubin (Direct / Conjugated)","category_order":4,"description":"Water-soluble bilirubin processed by the liver. Elevated direct bilirubin indicates hepatocellular disease or intrahepatic / extrahepatic bile duct obstruction (cholestasis)."},
  {"test_key":"bilirubin_indirect","display_name":"Bilirubin (Indirect / Unconjugated)","category_order":4,"description":"Bilirubin not yet processed by the liver. Elevated indirect bilirubin indicates increased red blood cell destruction (hemolysis), as in hemolytic anemia or sickle cell disease, or Gilbert's syndrome."},
  {"test_key":"ggt","display_name":"GGT (Gamma-Glutamyl Transferase)","category_order":4,"description":"A liver enzyme sensitive to alcohol intake and cholestasis. Elevated GGT alongside ALP confirms liver origin. Chronically elevated GGT is associated with excess alcohol use, fatty liver, and biliary disease."},
  {"test_key":"sgot","display_name":"SGOT / AST (Aspartate Aminotransferase)","category_order":4,"description":"A liver enzyme also found in heart, muscle, and kidneys. Elevated AST indicates hepatocellular damage. Very high levels (>1000 U/L) suggest acute hepatitis, ischemic hepatitis, or drug toxicity (e.g., acetaminophen)."},
  {"test_key":"sgpt","display_name":"SGPT / ALT (Alanine Aminotransferase)","category_order":4,"description":"The most liver-specific enzyme. Elevated ALT indicates hepatocellular injury from viral hepatitis, fatty liver, alcohol, or drug toxicity. Persistently elevated ALT warrants further investigation for chronic liver disease."},
  {"test_key":"sgot_sgpt_ratio","display_name":"SGOT / SGPT Ratio (De Ritis Ratio)","category_order":4,"description":"Ratio of AST to ALT. A ratio >2 suggests alcoholic liver disease. A ratio <1 is typical of viral hepatitis. Useful for differentiating the cause of liver damage."},
  {"test_key":"protein_total","display_name":"Total Protein (Serum)","category_order":4,"description":"Sum of albumin and globulin in blood. Low protein indicates malnutrition, liver disease, or protein-losing conditions (nephrotic syndrome). High protein may indicate dehydration or multiple myeloma."},
  {"test_key":"albumin_serum","display_name":"Albumin (Serum)","category_order":4,"description":"The most abundant plasma protein, made by the liver. Low albumin indicates malnutrition, chronic liver disease, nephrotic syndrome, or chronic inflammation. A key marker of nutritional status and liver synthetic function."},
  {"test_key":"globulin_serum","display_name":"Globulin (Serum)","category_order":4,"description":"Proteins including immunoglobulins and transport proteins. Elevated globulin may indicate chronic infection, autoimmune disease, or multiple myeloma. Low globulin may suggest immune deficiency or malabsorption."},
  {"test_key":"alb_glob_ratio","display_name":"Albumin / Globulin Ratio (A/G Ratio)","category_order":4,"description":"A ratio of albumin to globulin. Normal ratio is 1.0–2.5. Low A/G ratio (<1.0) suggests liver disease, chronic inflammation, or multiple myeloma. High ratio may indicate immunodeficiency."},
  {"test_key":"magnesium","display_name":"Magnesium (Serum)","category_order":4,"description":"Essential mineral for muscle and nerve function, blood glucose control, and protein synthesis. Low magnesium (hypomagnesemia) causes muscle cramps, arrhythmias, and anxiety. Often depleted by diuretics, alcohol, or poor diet."},
  {"test_key":"ldh","display_name":"LDH (Lactate Dehydrogenase)","category_order":4,"description":"An enzyme found in nearly all body tissues. Elevated LDH indicates tissue damage from myocardial infarction, hemolysis, liver disease, or cancer. Very high LDH is a marker of rapid cell turnover in lymphoma or leukemia."},
  {"test_key":"phosphorous","display_name":"Phosphorus (Serum)","category_order":4,"description":"Essential for bone formation, energy metabolism, and cell signaling. Low phosphorus (hypophosphatemia) causes muscle weakness and bone pain. Elevated phosphorus occurs in kidney failure and hypoparathyroidism."},
  {"test_key":"sodium","display_name":"Sodium (Serum)","category_order":4,"description":"The main extracellular electrolyte, critical for fluid balance and nerve/muscle function. Low sodium (hyponatremia) causes confusion, seizures. High sodium (hypernatremia) indicates dehydration or excess intake."},
  {"test_key":"potassium","display_name":"Potassium (Serum)","category_order":4,"description":"Essential intracellular electrolyte for heart rhythm and muscle function. Low potassium (hypokalemia) causes weakness, cramps, and arrhythmias. High potassium (hyperkalemia) is dangerous and can cause fatal cardiac arrest."},
  {"test_key":"chloride","display_name":"Chloride (Serum)","category_order":4,"description":"Major anion maintaining fluid and pH balance. Elevated chloride (hyperchloremia) occurs in dehydration or metabolic acidosis. Low chloride (hypochloremia) occurs with vomiting, diuretic use, or metabolic alkalosis."},
  {"test_key":"bun","display_name":"BUN (Blood Urea Nitrogen)","category_order":4,"description":"A byproduct of protein metabolism cleared by the kidneys. Elevated BUN indicates reduced kidney function, dehydration, or high protein diet. Low BUN may suggest liver disease, malnutrition, or overhydration."},
  {"test_key":"creatinine_serum","display_name":"Creatinine (Serum)","category_order":4,"description":"A waste product of muscle metabolism filtered by the kidneys. The most commonly used marker of kidney function. Elevated creatinine indicates reduced glomerular filtration rate (GFR) and impaired kidney function."},
  {"test_key":"bun_creat_ratio","display_name":"BUN / Creatinine Ratio","category_order":4,"description":"Differentiates pre-renal from intrinsic renal causes of kidney injury. Ratio >20 suggests pre-renal azotemia (dehydration, poor perfusion). Ratio 10–20 suggests intrinsic renal disease or post-renal obstruction."},
  {"test_key":"urea_calc","display_name":"Urea (Calculated)","category_order":4,"description":"The end product of protein metabolism in the liver, excreted by the kidneys. Elevated urea confirms kidney dysfunction or high protein catabolism. Calculated from BUN: Urea (mg/dL) = BUN × 2.14."},
  {"test_key":"calcium","display_name":"Calcium (Serum)","category_order":4,"description":"Essential for bone structure, muscle contraction, nerve signaling, and blood clotting. Low calcium (hypocalcemia) causes tetany and seizures. High calcium (hypercalcemia) indicates hyperparathyroidism or malignancy."},
  {"test_key":"urea_creat_ratio","display_name":"Urea / Creatinine Ratio","category_order":4,"description":"Similar in principle to BUN/Creatinine ratio but uses urea values. Elevated ratio suggests pre-renal causes of kidney impairment (dehydration, heart failure). Used alongside creatinine to assess kidney function context."},
  {"test_key":"uric_acid","display_name":"Uric Acid (Serum)","category_order":4,"description":"A breakdown product of purine metabolism. Elevated uric acid (hyperuricemia) can cause gout, uric acid kidney stones, and is associated with metabolic syndrome. Low uric acid may indicate Fanconi syndrome or Wilson's disease."},
  {"test_key":"egfr","display_name":"eGFR (Estimated Glomerular Filtration Rate)","category_order":4,"description":"Estimates kidney filtration capacity based on creatinine, age, sex, and race. Normal: ≥90 mL/min/1.73m². Stages of CKD: G1 (≥90), G2 (60–89), G3a (45–59), G3b (30–44), G4 (15–29), G5 (<15, kidney failure)."},
  {"test_key":"esr","display_name":"ESR (Erythrocyte Sedimentation Rate)","category_order":5,"description":"A non-specific marker of inflammation. Elevated ESR occurs in infection, autoimmune disease, cancer, and anemia. Used to monitor inflammatory conditions like rheumatoid arthritis and temporal arteritis."},
  {"test_key":"hemoglobin","display_name":"Hemoglobin","category_order":5,"description":"The oxygen-carrying protein in red blood cells. Low hemoglobin defines anemia. Normal: 13.5–17.5 g/dL (men), 12–15.5 g/dL (women). High hemoglobin suggests polycythemia vera, dehydration, or living at high altitude."},
  {"test_key":"pcv","display_name":"PCV / Hematocrit","category_order":5,"description":"Percentage of blood volume occupied by red blood cells. Parallels hemoglobin in diagnosing anemia and polycythemia. Normal: 41–53% (men), 36–46% (women)."},
  {"test_key":"rbc_total","display_name":"RBC Count (Total)","category_order":5,"description":"Total number of red blood cells per microliter of blood. Low RBC confirms anemia; high RBC indicates polycythemia or dehydration. Interpreted with hemoglobin and hematocrit for complete anemia workup."},
  {"test_key":"mcv","display_name":"MCV (Mean Corpuscular Volume)","category_order":5,"description":"Average size of red blood cells. Low MCV (microcytic anemia): iron deficiency or thalassemia. Normal MCV (normocytic): hemolysis or chronic disease. High MCV (macrocytic): B12/folate deficiency or alcoholism."},
  {"test_key":"mch","display_name":"MCH (Mean Corpuscular Hemoglobin)","category_order":5,"description":"Average amount of hemoglobin per red blood cell. Low MCH is seen in iron-deficiency anemia and thalassemia (microcytic, hypochromic). High MCH occurs in macrocytic anemias (B12/folate deficiency)."},
  {"test_key":"mchc","display_name":"MCHC (Mean Corpuscular Hemoglobin Concentration)","category_order":5,"description":"Concentration of hemoglobin in red blood cells. Low MCHC indicates hypochromic anemia (iron deficiency). High MCHC suggests spherocytosis or sickle cell disease."},
  {"test_key":"rdw_sd","display_name":"RDW-SD (Red Cell Distribution Width — SD)","category_order":5,"description":"Measures the variation in red blood cell size (standard deviation). Elevated RDW-SD indicates anisocytosis — a mix of differently sized red cells, seen in iron deficiency, B12 deficiency, or mixed anemias."},
  {"test_key":"rdw_cv","display_name":"RDW-CV (Red Cell Distribution Width — CV)","category_order":5,"description":"Coefficient of variation of red blood cell size. Elevated RDW-CV indicates increased size variability, helping differentiate iron-deficiency anemia (high RDW) from thalassemia (normal RDW)."},
  {"test_key":"rdwi","display_name":"RDWI (Red Cell Distribution Width Index)","category_order":5,"description":"A composite index combining MCV and RDW to differentiate types of anemia. Higher RDWI values suggest iron-deficiency anemia; lower values with low MCV suggest thalassemia."},
  {"test_key":"mentzer_index","display_name":"Mentzer Index","category_order":5,"description":"Calculated as MCV ÷ RBC count. Used to distinguish iron-deficiency anemia from beta-thalassemia trait. Value <13 suggests thalassemia; >13 suggests iron deficiency. A simple, non-invasive screening index."},
  {"test_key":"wbc_total","display_name":"WBC Count (Total)","category_order":5,"description":"Total number of white blood cells. Elevated WBC (leukocytosis) indicates infection, inflammation, or leukemia. Low WBC (leukopenia) suggests bone marrow suppression, viral infection, or autoimmune disease. Normal: 4,500–11,000 cells/µL."},
  {"test_key":"neutrophils_pct","display_name":"Neutrophils (%)","category_order":5,"description":"Percentage of WBCs that are neutrophils, the first responders to bacterial infections. Normal: 50–70%. Elevated neutrophils (neutrophilia) indicate bacterial infection, stress, or steroid use. Low levels (neutropenia) increase infection risk."},
  {"test_key":"lymphocytes_pct","display_name":"Lymphocytes (%)","category_order":5,"description":"Percentage of WBCs that are lymphocytes, key immune cells (B and T cells). Elevated (lymphocytosis) occurs in viral infections and lymphocytic leukemia. Low (lymphopenia) occurs in HIV, steroid therapy, or sepsis."},
  {"test_key":"monocytes_pct","display_name":"Monocytes (%)","category_order":5,"description":"Percentage of WBCs that are monocytes, which mature into macrophages. Elevated monocytes (monocytosis) occur in chronic infections, autoimmune disease, and certain leukemias. Normal: 2–8%."},
  {"test_key":"eosinophils_pct","display_name":"Eosinophils (%)","category_order":5,"description":"Percentage of WBCs involved in allergic responses and fighting parasites. Elevated eosinophils (eosinophilia) indicate allergies, asthma, parasitic infection, or eosinophilic disorders. Normal: 1–4%."},
  {"test_key":"basophils_pct","display_name":"Basophils (%)","category_order":5,"description":"Rarest white blood cell type, involved in allergic and inflammatory reactions. Elevated basophils (basophilia) occur in allergic reactions, hypothyroidism, and myeloproliferative disorders. Normal: 0–1%."},
  {"test_key":"ig_pct","display_name":"Immature Granulocytes (%)","category_order":5,"description":"Percentage of immature white blood cells (band cells, metamyelocytes, etc.) in circulation. Elevated IG% is a marker of serious infection, sepsis, or bone marrow stress. Normal is 0–1% on automated CBC."},
  {"test_key":"nrbc_pct","display_name":"NRBC (%)","category_order":5,"description":"Nucleated red blood cells as a percentage of WBCs. Normally absent from adult peripheral blood. Presence indicates severe stress to bone marrow from hemolysis, hypoxia, myelofibrosis, or thalassemia."},
  {"test_key":"neutrophils_abs","display_name":"Neutrophils (Absolute)","category_order":5,"description":"Absolute count of neutrophils. ANC (Absolute Neutrophil Count) <1500 cells/µL indicates neutropenia; <500 is severe neutropenia with very high infection risk. ANC >7500 indicates neutrophilia from infection or inflammation."},
  {"test_key":"lymphocytes_abs","display_name":"Lymphocytes (Absolute)","category_order":5,"description":"Absolute count of lymphocytes. Absolute lymphopenia (<1000/µL in adults) is associated with HIV, immunosuppression, or severe sepsis. Absolute lymphocytosis suggests viral infection or lymphocytic leukemia."},
  {"test_key":"monocytes_abs","display_name":"Monocytes (Absolute)","category_order":5,"description":"Absolute count of monocytes. Absolute monocytosis (>800/µL) is seen in chronic infections (TB, malaria), monocytic leukemia, and inflammatory bowel disease. Used alongside differential percentage for clinical context."},
  {"test_key":"basophils_abs","display_name":"Basophils (Absolute)","category_order":5,"description":"Absolute count of basophils. Absolute basophilia occurs in myeloproliferative neoplasms (particularly CML), hypothyroidism, and inflammatory conditions. Normal absolute count: 0–100/µL."},
  {"test_key":"eosinophils_abs","display_name":"Eosinophils (Absolute)","category_order":5,"description":"Absolute count of eosinophils. Absolute eosinophilia (>500/µL) suggests allergic disease, parasitic infection, or hypereosinophilic syndrome. Counts >1500/µL can cause organ damage."},
  {"test_key":"ig_abs","display_name":"Immature Granulocytes (Absolute)","category_order":5,"description":"Absolute count of immature white blood cells. Elevated values indicate left-shifted leukocytosis, commonly seen in sepsis, severe infection, or bone marrow recovery after chemotherapy."},
  {"test_key":"nrbc_abs","display_name":"NRBC (Absolute)","category_order":5,"description":"Absolute count of nucleated red blood cells in peripheral blood. Any detectable value in adults is abnormal and prompts investigation for hemolytic anemia, thalassemia, marrow replacement, or severe hypoxia."},
  {"test_key":"platelet_count","display_name":"Platelet Count","category_order":5,"description":"Number of platelets involved in blood clotting. Low platelets (thrombocytopenia, <150,000/µL) increase bleeding risk from ITP, dengue, or bone marrow suppression. High platelets (thrombocytosis) occur in reactive states or myeloproliferative disease."},
  {"test_key":"mpv","display_name":"MPV (Mean Platelet Volume)","category_order":5,"description":"Average size of platelets. Larger platelets are more active. Elevated MPV with low platelet count suggests increased platelet destruction (ITP). Low MPV with thrombocytopenia may indicate bone marrow failure."},
  {"test_key":"pdw","display_name":"PDW (Platelet Distribution Width)","category_order":5,"description":"Variation in platelet size. Elevated PDW indicates platelet anisocytosis, seen in ITP, vitamin B12 deficiency, thrombotic disorders, and platelet activation. Normal variation is seen in healthy individuals."},
  {"test_key":"plcr","display_name":"PLCR (Platelet Large Cell Ratio)","category_order":5,"description":"Percentage of large platelets in total platelet count. Elevated PLCR alongside elevated MPV indicates increased platelet activity, as seen in cardiovascular disease, thrombocytopenia, and diabetic angiopathy."},
  {"test_key":"pct","display_name":"PCT (Plateletcrit)","category_order":5,"description":"Percentage of blood volume occupied by platelets, analogous to hematocrit for red cells. Low PCT occurs with thrombocytopenia; elevated PCT with thrombocytosis. A rarely used but comprehensive platelet mass index."},
  {"test_key":"urine_volume","display_name":"Urine Volume","category_order":6,"description":"Total urine produced. Normal daily output: 800–2000 mL. Polyuria (>3000 mL/day) may indicate diabetes insipidus or mellitus. Oliguria (<400 mL/day) occurs in dehydration or kidney failure."},
  {"test_key":"urine_colour","display_name":"Urine Colour","category_order":6,"description":"Normal color is pale to dark yellow depending on concentration. Red/brown urine indicates blood, myoglobin, or beets. Dark brown suggests bilirubinuria. Colorless urine indicates overhydration or diabetes insipidus."},
  {"test_key":"urine_appearance","display_name":"Urine Appearance","category_order":6,"description":"Normal urine is clear. Cloudy urine may indicate pyuria (pus cells), bacteria, phosphates, or cells. Foamy urine can suggest proteinuria. Turbid urine warrants microscopy to identify the cause."},
  {"test_key":"urine_specific_gravity","display_name":"Urine Specific Gravity","category_order":6,"description":"Measures urine concentration relative to water. Normal: 1.005–1.030. Low (<1.005) suggests diabetes insipidus or overhydration. High (>1.030) indicates dehydration or SIADH. Reflects the kidney's concentrating ability."},
  {"test_key":"urine_ph","display_name":"Urine pH","category_order":6,"description":"Measures acidity or alkalinity of urine. Normal range: 4.5–8.0. Acidic urine can precipitate uric acid stones. Alkaline urine is seen in UTI, renal tubular acidosis, or high vegetable diet. Used in kidney stone management."},
  {"test_key":"urine_protein","display_name":"Urine Protein","category_order":6,"description":"Protein should not normally be present in urine. Proteinuria indicates glomerular damage (nephrotic syndrome), hypertension, or diabetic nephropathy. Trace protein can occur after heavy exercise or fever."},
  {"test_key":"urine_glucose","display_name":"Urine Glucose","category_order":6,"description":"Glucose is normally absent in urine. Glycosuria occurs when blood glucose exceeds the renal threshold (~180 mg/dL) in diabetes mellitus. Can also occur in Fanconi syndrome with normal blood glucose."},
  {"test_key":"urine_ketone","display_name":"Urine Ketones","category_order":6,"description":"Ketones are absent in normal urine. Ketonuria indicates diabetic ketoacidosis, starvation, prolonged fasting, or very low carbohydrate diets. A key test for diabetic ketoacidosis (DKA) diagnosis and monitoring."},
  {"test_key":"urine_bilirubin","display_name":"Urine Bilirubin","category_order":6,"description":"Bilirubin is not normally present in urine. Bilirubinuria indicates liver disease (hepatitis, cirrhosis) or biliary obstruction. Conjugated (direct) bilirubin is water-soluble and passes into urine when levels are elevated."},
  {"test_key":"urine_urobilinogen","display_name":"Urine Urobilinogen","category_order":6,"description":"A byproduct of bilirubin metabolism in the gut. Normal: 0.1–1.0 mg/dL. Elevated urobilinogen suggests hemolysis or liver disease. Absent urobilinogen indicates complete bile duct obstruction."},
  {"test_key":"urine_bile_salt","display_name":"Urine Bile Salts","category_order":6,"description":"Bile salts appear in urine when there is obstructive jaundice or severe liver disease preventing bile from entering the intestine normally. Their presence helps distinguish obstructive from hemolytic jaundice."},
  {"test_key":"urine_bile_pigment","display_name":"Urine Bile Pigment","category_order":6,"description":"Bile pigments (mainly bilirubin) in urine indicate conjugated hyperbilirubinemia. Present in hepatocellular jaundice and obstructive jaundice, but absent in pre-hepatic (hemolytic) jaundice."},
  {"test_key":"urine_blood","display_name":"Urine Blood (Occult)","category_order":6,"description":"Detects hemoglobin or myoglobin. Positive result may indicate hematuria (blood in urine) from UTI, kidney stones, glomerulonephritis, or bladder cancer. Myoglobinuria from rhabdomyolysis also gives a positive test."},
  {"test_key":"urine_nitrite","display_name":"Urine Nitrite","category_order":6,"description":"Bacteria that reduce nitrate to nitrite produce a positive test. A positive nitrite result strongly suggests a urinary tract infection (UTI), especially with Gram-negative organisms like E. coli. Used for rapid UTI screening."},
  {"test_key":"urine_leucocyte_esterase","display_name":"Urine Leucocyte Esterase","category_order":6,"description":"An enzyme released by neutrophils (pus cells). A positive test indicates pyuria and is a sensitive marker for urinary tract infection. Interpreted alongside nitrite for UTI diagnosis."},
  {"test_key":"urine_mucus","display_name":"Urine Mucus","category_order":6,"description":"Mucus threads can be a normal finding or indicate urinary tract inflammation. Significant amounts of mucus may suggest UTI, urethritis, or bladder irritation."},
  {"test_key":"urine_rbc","display_name":"Urine RBC (Red Blood Cells)","category_order":6,"description":"Normal: 0–2 RBCs per high-power field. Elevated RBCs (hematuria) may indicate kidney stones, glomerulonephritis, UTI, bladder cancer, or trauma. Dysmorphic RBCs suggest glomerular origin."},
  {"test_key":"urine_pus_cells","display_name":"Urine Pus Cells (WBCs)","category_order":6,"description":"White blood cells in urine (pyuria). Normal: 0–5 WBCs per high-power field. >5 WBCs/HPF indicates UTI, urethritis, or interstitial nephritis. Sterile pyuria may indicate TB or chlamydia."},
  {"test_key":"urine_epithelial_cells","display_name":"Urine Epithelial Cells","category_order":6,"description":"Small numbers are normal (from urinary tract lining). Large numbers of squamous epithelial cells suggest specimen contamination. Renal tubular epithelial cells indicate renal parenchymal damage."},
  {"test_key":"urine_casts","display_name":"Urine Casts","category_order":6,"description":"Cylindrical structures formed in kidney tubules. Hyaline casts are normal in small amounts. RBC casts indicate glomerulonephritis; WBC casts indicate pyelonephritis or interstitial nephritis; granular/waxy casts indicate chronic renal disease."},
  {"test_key":"urine_crystals","display_name":"Urine Crystals","category_order":6,"description":"Crystals can form at certain pH levels and temperatures. Calcium oxalate crystals are common in kidney stone formers. Uric acid crystals occur in gout and high-purine diets. Struvite crystals indicate infection-related stones."},
  {"test_key":"urine_bacteria","display_name":"Urine Bacteria","category_order":6,"description":"Normal urine is sterile. Any bacteria on microscopy (bacteriuria) in a properly collected specimen suggests UTI. Confirmed with urine culture for organism identification and antibiotic sensitivity."},
  {"test_key":"urine_yeast","display_name":"Urine Yeast","category_order":6,"description":"Yeast (usually Candida) in urine indicates fungal UTI (candiduria), commonly seen in diabetic patients, those on broad-spectrum antibiotics, or immunocompromised individuals. Requires antifungal treatment if symptomatic."},
  {"test_key":"urine_parasite","display_name":"Urine Parasite","category_order":6,"description":"Parasites in urine are rare in most regions. Trichomonas vaginalis can be detected in urine. Schistosoma haematobium causes urogenital schistosomiasis with terminal hematuria, diagnosed by urine microscopy."},
];

const NEW_TESTS = [
  {"test_key":"apo_a1","display_name":"Apolipoprotein A1 (APO-A1)","category":"Cardiac, Iron & Diabetes","category_order":2,"description":"The main protein component of HDL (\"good\") cholesterol. APO-A1 facilitates reverse cholesterol transport. Low levels are an independent risk factor for cardiovascular disease. Normal: 86–152 mg/dL (men), 94–162 mg/dL (women).","is_active":true},
  {"test_key":"apo_b","display_name":"Apolipoprotein B (APO-B)","category":"Cardiac, Iron & Diabetes","category_order":2,"description":"The main protein in LDL and VLDL (\"bad\") cholesterol particles. Each atherogenic lipoprotein carries one APO-B molecule, making it a precise measure of particle count. Elevated APO-B strongly predicts cardiovascular risk.","is_active":true},
  {"test_key":"apo_b_a1_ratio","display_name":"APO B / APO A1 Ratio","category":"Cardiac, Iron & Diabetes","category_order":2,"description":"Ratio of atherogenic (APO-B) to anti-atherogenic (APO-A1) lipoproteins. Normal: 0.40–1.26 (men), 0.38–1.14 (women). Considered a superior cardiovascular risk predictor compared to LDL or total cholesterol alone.","is_active":true},
  {"test_key":"avg_blood_glucose","display_name":"Average Blood Glucose (Estimated)","category":"Cardiac, Iron & Diabetes","category_order":2,"description":"Estimated average blood glucose over the past 2–3 months, derived from HbA1c. Normal: 90–120 mg/dL. Useful for understanding day-to-day glucose exposure in a clinically familiar unit (mg/dL) alongside HbA1c.","is_active":true},
];

exports.up = async (knex) => {
  // Update existing tests with descriptions, display names, and category_order
  for (const test of TEST_UPDATES) {
    await knex('test_definitions')
      .where('test_key', test.test_key)
      .update({
        display_name: test.display_name,
        description: test.description,
        category_order: test.category_order,
      });
  }

  // Insert new tests that were missing
  const maxSort = await knex('test_definitions')
    .where('category', 'Cardiac, Iron & Diabetes')
    .max('sort_order as max')
    .first();
  let sortOrder = (maxSort?.max || 15) + 1;

  for (const test of NEW_TESTS) {
    await knex('test_definitions').insert({
      ...test,
      sort_order: sortOrder++,
    });
  }
};

exports.down = async (knex) => {
  // Remove newly added tests
  const newKeys = NEW_TESTS.map(t => t.test_key);
  await knex('test_definitions').whereIn('test_key', newKeys).delete();

  // Clear description and category_order from existing tests
  await knex('test_definitions').update({ description: null, category_order: 0 });
};
